#!/usr/bin/env python3

from analyzer import Analyzer
import helpers
import sys
import nltk
import os
from termcolor import colored

# ensure proper usage
if len(sys.argv) != 2:
    sys.exit("Usage: ./tweets handle")

#absolute paths to lists  
positives = os.path.join(sys.path[0], "positive-words.txt")
negatives = os.path.join(sys.path[0], "negative-words.txt")

# instantiate analyzer
analyzer = Analyzer(positives, negatives)

screen_name = sys.argv[1].strip('@')

tweets = helpers.get_user_timeline(screen_name, 50)

if tweets == None:
    sys.exit("Could not locate user")

for tweet in tweets:
    score = analyzer.analyze(tweet)
    if score > 0:
        print(colored("{} {}".format(score, tweet), "green"))
    elif score < 0:
        print(colored("{} {}".format(score, tweet), "red"))
    else:
        print(colored("{} {}".format(score, tweet), "yellow"))
